# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphs.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_graphs(object):
    def setupUi(self, graphs):
        graphs.setObjectName("graphs")
        graphs.resize(1100, 848)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(graphs.sizePolicy().hasHeightForWidth())
        graphs.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(graphs)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.graphicsView = PlotWidget(graphs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_6.addWidget(self.graphicsView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.AT_X = QtWidgets.QPushButton(graphs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AT_X.sizePolicy().hasHeightForWidth())
        self.AT_X.setSizePolicy(sizePolicy)
        self.AT_X.setMaximumSize(QtCore.QSize(16777215, 50))
        self.AT_X.setObjectName("AT_X")
        self.verticalLayout.addWidget(self.AT_X)
        self.AT_Y = QtWidgets.QPushButton(graphs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AT_Y.sizePolicy().hasHeightForWidth())
        self.AT_Y.setSizePolicy(sizePolicy)
        self.AT_Y.setMaximumSize(QtCore.QSize(16777215, 50))
        self.AT_Y.setObjectName("AT_Y")
        self.verticalLayout.addWidget(self.AT_Y)
        self.T_XY = QtWidgets.QPushButton(graphs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T_XY.sizePolicy().hasHeightForWidth())
        self.T_XY.setSizePolicy(sizePolicy)
        self.T_XY.setMaximumSize(QtCore.QSize(16777215, 50))
        self.T_XY.setObjectName("T_XY")
        self.verticalLayout.addWidget(self.T_XY)
        self.AT_Z = QtWidgets.QPushButton(graphs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AT_Z.sizePolicy().hasHeightForWidth())
        self.AT_Z.setSizePolicy(sizePolicy)
        self.AT_Z.setMaximumSize(QtCore.QSize(16777215, 50))
        self.AT_Z.setObjectName("AT_Z")
        self.verticalLayout.addWidget(self.AT_Z)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.AB_X = QtWidgets.QPushButton(graphs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AB_X.sizePolicy().hasHeightForWidth())
        self.AB_X.setSizePolicy(sizePolicy)
        self.AB_X.setMaximumSize(QtCore.QSize(16777215, 50))
        self.AB_X.setObjectName("AB_X")
        self.verticalLayout_5.addWidget(self.AB_X)
        self.AB_Y = QtWidgets.QPushButton(graphs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AB_Y.sizePolicy().hasHeightForWidth())
        self.AB_Y.setSizePolicy(sizePolicy)
        self.AB_Y.setMaximumSize(QtCore.QSize(16777215, 50))
        self.AB_Y.setObjectName("AB_Y")
        self.verticalLayout_5.addWidget(self.AB_Y)
        self.B_XY = QtWidgets.QPushButton(graphs)
        self.B_XY.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B_XY.sizePolicy().hasHeightForWidth())
        self.B_XY.setSizePolicy(sizePolicy)
        self.B_XY.setMaximumSize(QtCore.QSize(16777215, 50))
        self.B_XY.setObjectName("B_XY")
        self.verticalLayout_5.addWidget(self.B_XY)
        self.AB_Z = QtWidgets.QPushButton(graphs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AB_Z.sizePolicy().hasHeightForWidth())
        self.AB_Z.setSizePolicy(sizePolicy)
        self.AB_Z.setMaximumSize(QtCore.QSize(16777215, 50))
        self.AB_Z.setObjectName("AB_Z")
        self.verticalLayout_5.addWidget(self.AB_Z)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gx_t = QtWidgets.QPushButton(graphs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gx_t.sizePolicy().hasHeightForWidth())
        self.gx_t.setSizePolicy(sizePolicy)
        self.gx_t.setMaximumSize(QtCore.QSize(16777215, 50))
        self.gx_t.setObjectName("gx_t")
        self.verticalLayout_2.addWidget(self.gx_t)
        self.gy_t = QtWidgets.QPushButton(graphs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gy_t.sizePolicy().hasHeightForWidth())
        self.gy_t.setSizePolicy(sizePolicy)
        self.gy_t.setMaximumSize(QtCore.QSize(16777215, 50))
        self.gy_t.setObjectName("gy_t")
        self.verticalLayout_2.addWidget(self.gy_t)
        self.gz_t = QtWidgets.QPushButton(graphs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gz_t.sizePolicy().hasHeightForWidth())
        self.gz_t.setSizePolicy(sizePolicy)
        self.gz_t.setMaximumSize(QtCore.QSize(16777215, 50))
        self.gz_t.setObjectName("gz_t")
        self.verticalLayout_2.addWidget(self.gz_t)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gx_b = QtWidgets.QPushButton(graphs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gx_b.sizePolicy().hasHeightForWidth())
        self.gx_b.setSizePolicy(sizePolicy)
        self.gx_b.setMaximumSize(QtCore.QSize(16777215, 50))
        self.gx_b.setObjectName("gx_b")
        self.verticalLayout_3.addWidget(self.gx_b)
        self.gy_b = QtWidgets.QPushButton(graphs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gy_b.sizePolicy().hasHeightForWidth())
        self.gy_b.setSizePolicy(sizePolicy)
        self.gy_b.setMaximumSize(QtCore.QSize(16777215, 50))
        self.gy_b.setObjectName("gy_b")
        self.verticalLayout_3.addWidget(self.gy_b)
        self.gz_b = QtWidgets.QPushButton(graphs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gz_b.sizePolicy().hasHeightForWidth())
        self.gz_b.setSizePolicy(sizePolicy)
        self.gz_b.setMaximumSize(QtCore.QSize(16777215, 50))
        self.gz_b.setObjectName("gz_b")
        self.verticalLayout_3.addWidget(self.gz_b)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pressure_t = QtWidgets.QPushButton(graphs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pressure_t.sizePolicy().hasHeightForWidth())
        self.pressure_t.setSizePolicy(sizePolicy)
        self.pressure_t.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pressure_t.setObjectName("pressure_t")
        self.verticalLayout_7.addWidget(self.pressure_t)
        self.pressure_b = QtWidgets.QPushButton(graphs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pressure_b.sizePolicy().hasHeightForWidth())
        self.pressure_b.setSizePolicy(sizePolicy)
        self.pressure_b.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pressure_b.setObjectName("pressure_b")
        self.verticalLayout_7.addWidget(self.pressure_b)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 103, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem)
        self.knee_angle = QtWidgets.QPushButton(graphs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.knee_angle.sizePolicy().hasHeightForWidth())
        self.knee_angle.setSizePolicy(sizePolicy)
        self.knee_angle.setMinimumSize(QtCore.QSize(0, 50))
        self.knee_angle.setMaximumSize(QtCore.QSize(16777215, 50))
        self.knee_angle.setObjectName("knee_angle")
        self.verticalLayout_4.addWidget(self.knee_angle)
        spacerItem1 = QtWidgets.QSpacerItem(40, 93, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem1)
        self.velocity = QtWidgets.QPushButton(graphs)
        self.velocity.setMinimumSize(QtCore.QSize(0, 50))
        self.velocity.setObjectName("velocity")
        self.verticalLayout_4.addWidget(self.velocity)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(graphs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.ButtonPressed = QtWidgets.QLabel(graphs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonPressed.sizePolicy().hasHeightForWidth())
        self.ButtonPressed.setSizePolicy(sizePolicy)
        self.ButtonPressed.setObjectName("ButtonPressed")
        self.verticalLayout_4.addWidget(self.ButtonPressed)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 0, 1, 1)

        self.retranslateUi(graphs)
        QtCore.QMetaObject.connectSlotsByName(graphs)

    def retranslateUi(self, graphs):
        _translate = QtCore.QCoreApplication.translate
        graphs.setWindowTitle(_translate("graphs", "Form"))
        self.AT_X.setText(_translate("graphs", "AT X"))
        self.AT_Y.setText(_translate("graphs", "AT Y"))
        self.T_XY.setText(_translate("graphs", "Top Magnitude X Y"))
        self.AT_Z.setText(_translate("graphs", "AT Z"))
        self.AB_X.setText(_translate("graphs", "AB X"))
        self.AB_Y.setText(_translate("graphs", "AB Y"))
        self.B_XY.setText(_translate("graphs", "Bottom Magnitude X Y"))
        self.AB_Z.setText(_translate("graphs", "AB Z"))
        self.gx_t.setText(_translate("graphs", "Gyro Top X"))
        self.gy_t.setText(_translate("graphs", "Gyro Top Y"))
        self.gz_t.setText(_translate("graphs", "Gyro Top Z"))
        self.gx_b.setText(_translate("graphs", "Gyro Bottom X"))
        self.gy_b.setText(_translate("graphs", "Gyro Bottom Y"))
        self.gz_b.setText(_translate("graphs", "Gyro Bottom Z"))
        self.pressure_t.setText(_translate("graphs", "Pressure Top"))
        self.pressure_b.setText(_translate("graphs", "Pressure Bottom"))
        self.knee_angle.setText(_translate("graphs", "Knee Angle"))
        self.velocity.setText(_translate("graphs", "Velocity"))
        self.label.setText(_translate("graphs", "Last Button Pressed:"))
        self.ButtonPressed.setText(_translate("graphs", "No Button Pressed"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    graphs = QtWidgets.QWidget()
    ui = Ui_graphs()
    ui.setupUi(graphs)
    graphs.show()
    sys.exit(app.exec_())
