# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'playerStats.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlayerStats(object):
    def setupUi(self, PlayerStats):
        PlayerStats.setObjectName("PlayerStats")
        PlayerStats.resize(793, 676)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PlayerStats.sizePolicy().hasHeightForWidth())
        PlayerStats.setSizePolicy(sizePolicy)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(PlayerStats)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.splitter = QtWidgets.QSplitter(PlayerStats)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.NumJumps = QtWidgets.QLCDNumber(self.widget)
        self.NumJumps.setObjectName("NumJumps")
        self.horizontalLayout_7.addWidget(self.NumJumps)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.NumSteps = QtWidgets.QLCDNumber(self.widget1)
        self.NumSteps.setObjectName("NumSteps")
        self.horizontalLayout_6.addWidget(self.NumSteps)
        self.label = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.widget2 = QtWidgets.QWidget(self.splitter)
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.NumMinutes = QtWidgets.QLCDNumber(self.widget2)
        self.NumMinutes.setObjectName("NumMinutes")
        self.horizontalLayout_5.addWidget(self.NumMinutes)
        self.label_5 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.widget3 = QtWidgets.QWidget(self.splitter)
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.NumImpacts = QtWidgets.QLCDNumber(self.widget3)
        self.NumImpacts.setObjectName("NumImpacts")
        self.horizontalLayout_4.addWidget(self.NumImpacts)
        self.label_3 = QtWidgets.QLabel(self.widget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(101, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(True)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(158, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.TimeSpentLabel = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.TimeSpentLabel.setFont(font)
        self.TimeSpentLabel.setObjectName("TimeSpentLabel")
        self.widget4 = QtWidgets.QWidget(self.splitter)
        self.widget4.setObjectName("widget4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NumRun = QtWidgets.QLCDNumber(self.widget4)
        self.NumRun.setObjectName("NumRun")
        self.horizontalLayout.addWidget(self.NumRun)
        self.label_7 = QtWidgets.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.widget5 = QtWidgets.QWidget(self.splitter)
        self.widget5.setObjectName("widget5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget5)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.NumSprint = QtWidgets.QLCDNumber(self.widget5)
        self.NumSprint.setObjectName("NumSprint")
        self.horizontalLayout_2.addWidget(self.NumSprint)
        self.label_8 = QtWidgets.QLabel(self.widget5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.widget6 = QtWidgets.QWidget(self.splitter)
        self.widget6.setObjectName("widget6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget6)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.NumWalk = QtWidgets.QLCDNumber(self.widget6)
        self.NumWalk.setObjectName("NumWalk")
        self.horizontalLayout_3.addWidget(self.NumWalk)
        self.label_9 = QtWidgets.QLabel(self.widget6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.ProgressbarLabel = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ProgressbarLabel.setFont(font)
        self.ProgressbarLabel.setObjectName("ProgressbarLabel")
        self.LoadPercent = QtWidgets.QProgressBar(self.splitter)
        self.LoadPercent.setProperty("value", 24)
        self.LoadPercent.setObjectName("LoadPercent")
        self.horizontalLayout_8.addWidget(self.splitter)

        self.retranslateUi(PlayerStats)
        QtCore.QMetaObject.connectSlotsByName(PlayerStats)

    def retranslateUi(self, PlayerStats):
        _translate = QtCore.QCoreApplication.translate
        PlayerStats.setWindowTitle(_translate("PlayerStats", "Form"))
        self.label_2.setText(_translate("PlayerStats", "Jumps           "))
        self.label.setText(_translate("PlayerStats", "Steps            "))
        self.label_5.setText(_translate("PlayerStats", "Minutes Played"))
        self.label_3.setText(_translate("PlayerStats", "High Impact Events       "))
        self.TimeSpentLabel.setText(_translate("PlayerStats", "Time Spent:"))
        self.label_7.setText(_translate("PlayerStats", "Running"))
        self.label_8.setText(_translate("PlayerStats", "Sprinting"))
        self.label_9.setText(_translate("PlayerStats", "Walking"))
        self.ProgressbarLabel.setText(_translate("PlayerStats", "Percentage of limit Played"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PlayerStats = QtWidgets.QWidget()
    ui = Ui_PlayerStats()
    ui.setupUi(PlayerStats)
    PlayerStats.show()
    sys.exit(app.exec_())
